targets:
  $default:
    builders:
      moor_generator:
        options:
          use_data_class_name_for_companions: true



# flutter packages pub run build_runner build
# flutter packages pub run build_runner watch